# Generated by Django 4.1.3 on 2022-11-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title',
            new_name='city',
        ),
    ]
