# Generated by Django 4.1.3 on 2022-11-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_job_title_user_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
