# Generated by Django 4.1.3 on 2023-01-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_options_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='signature',
            new_name='bio',
        ),
    ]
